### ISSUE TITLE
Setting to reduce unlock balance wait time after send

### ISSUE THREAD

**Issue by kunalransing** [monero-ecosystem/monero-java#21]
Hi,
For my old project, I used  0.0.1-SNAPSHOT from here: https://github.com/woodser/monero-wallet-java.git  
When we send amount then have to wait for a long time to send next since unlock balance is zero so how & where to do setting so that we can reduce unlock balance wait time after send?
Thanks.

**Comment by woodser** [comment]
This is not a dynamic setting supported in the Java library.  The Monero Core software can be re-compiled to lower the minimum number of blocks before received funds or change can be spent [here](https://github.com/monero-project/monero/blob/ed09652a174e80cff78f0bfb9e586292d4a1575f/src/cryptonote_config.h#L48), but lowering this value increases the risk of your wallet's transactions being invalidated by re-orgs, which are not uncommon.  In the future, it may be possible to safely lower or remove the limit if [changes](https://github.com/monero-project/monero/issues/5810) are made to Monero Core.

**Comment by kunalransing** [comment]
Ok. Thank you very much for your reply.
Is there any other way to send without the wait? How exchanges handle such things, what do you suggest? 
Thanks.

**Comment by woodser** [comment]
One can send transactions to their own wallet in order to break up the wallet's spendable outputs.  Transactions can be sent without waiting until the wallet runs out of spendable outputs to satisfy the request and must therefore wait for change or an incoming transfer to unlock.

Among other ways, an easy way to break up the wallet's outputs is to create a transaction which transfers the wallet's balance across its own subaddresses.  Up to 16 subaddresses can be specified in a single transaction.

**Comment by kunalransing** [comment]
Ok. Thanks. I will try above way.
